# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('workrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='address_apt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='address_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='address_state',
            field=localflavor.us.models.USStateField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='address_zip',
            field=localflavor.us.models.USZipCodeField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
