# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrequest', '0002_auto_20170507_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='salesperson',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
