# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesperson', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('address_apt', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', localflavor.us.models.USStateField(max_length=2)),
                ('address_zip', localflavor.us.models.USZipCodeField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
