# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accountuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
