# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170511_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='username',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the user active? Uncheck this instead of deleting users', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Allow the user to log into the admin site', verbose_name='staff user'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
