# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170512_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
